image: gradle:alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  #  - build
  - test

#build:
#  stage: build
#  script: gradle --build-cache assemble
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#    paths:
#      - build
#      - .gradle

test:
  stage: test
  script:
    - gradle test
    - pwd
    - ls
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml