image: java:8-jdk

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script:
    - ./gradlew test

  artifacts:
    paths:
      - build/reports/tests/test/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir public
    - mv build/reports/tests/test/* public
  artifacts:
    paths:
      - public

  only:
    - master

